# Generated by Django 3.2.7 on 2021-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(max_length=128)),
                ('markdown_file', models.CharField(max_length=512, unique=True)),
            ],
        ),
    ]
