name: "🚀 Enhancement"
description: Request an enhancement
title: "🚀 [ENHANCEMENT] <title>"
labels: [
  "enhancement"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the enhancement you would like"
    validations:
      required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: "Possible Solution"
      description: Describe the solution you would like to see
      placeholder: Describe in a few lines a possible solution
    validations:
      required: true

  - type: checkboxes
    id: has_issue
    attributes:
      label: "Does this enhancement request have an existing issue?"
      description: "If so, please provide the issue number in the additional information field"
      options:
        - label: "Yes"

  - type: textarea
    id: additional_info
    attributes:
      label: "Additional Information"
      description: Provide additional information
      placeholder: Enter any additional information here
    validations:
      required: false