export interface Errno {
  name: string;
  number: number;
  message: string;
}

export const Errno = {
  EPERM: { "name": "EPERM", "number": 1, message: "Operation not permitted" },
  ENOENT: {
    "name": "ENOENT",
    "number": 2,
    message: "No such file or directory",
  },
  ESRCH: { "name": "ESRCH", "number": 3, message: "No such process" },
  EINTR: { "name": "EINTR", "number": 4, message: "Interrupted system call" },
  EIO: { "name": "EIO", "number": 5, message: "Input/output error" },
  ENXIO: { "name": "ENXIO", "number": 6, message: "No such device or address" },
  E2BIG: { "name": "E2BIG", "number": 7, message: "Argument list too long" },
  ENOEXEC: { "name": "ENOEXEC", "number": 8, message: "Exec format error" },
  EBADF: { "name": "EBADF", "number": 9, message: "Bad file descriptor" },
  ECHILD: { "name": "ECHILD", "number": 10, message: "No child processes" },
  EAGAIN: {
    "name": "EAGAIN",
    "number": 11,
    message: "Resource temporarily unavailable",
  },
  ENOMEM: { "name": "ENOMEM", "number": 12, message: "Cannot allocate memory" },
  EACCES: { "name": "EACCES", "number": 13, message: "Permission denied" },
  EFAULT: { "name": "EFAULT", "number": 14, message: "Bad address" },
  ENOTBLK: {
    "name": "ENOTBLK",
    "number": 15,
    message: "Block device required",
  },
  EBUSY: { "name": "EBUSY", "number": 16, message: "Device or resource busy" },
  EEXIST: { "name": "EEXIST", "number": 17, message: "File exists" },
  EXDEV: {
    "name": "EXDEV",
    "number": 18,
    message: "Invalid cross-device link",
  },
  ENODEV: { "name": "ENODEV", "number": 19, message: "No such device" },
  ENOTDIR: { "name": "ENOTDIR", "number": 20, message: "Not a directory" },
  EISDIR: { "name": "EISDIR", "number": 21, message: "Is a directory" },
  EINVAL: { "name": "EINVAL", "number": 22, message: "Invalid argument" },
  ENFILE: {
    "name": "ENFILE",
    "number": 23,
    message: "Too many open files in system",
  },
  EMFILE: { "name": "EMFILE", "number": 24, message: "Too many open files" },
  ENOTTY: {
    "name": "ENOTTY",
    "number": 25,
    message: "Inappropriate ioctl for device",
  },
  ETXTBSY: { "name": "ETXTBSY", "number": 26, message: "Text file busy" },
  EFBIG: { "name": "EFBIG", "number": 27, message: "File too large" },
  ENOSPC: {
    "name": "ENOSPC",
    "number": 28,
    message: "No space left on device",
  },
  ESPIPE: { "name": "ESPIPE", "number": 29, message: "Illegal seek" },
  EROFS: { "name": "EROFS", "number": 30, message: "Read-only file system" },
  EMLINK: { "name": "EMLINK", "number": 31, message: "Too many links" },
  EPIPE: { "name": "EPIPE", "number": 32, message: "Broken pipe" },
  EDOM: {
    "name": "EDOM",
    "number": 33,
    message: "Numerical argument out of domain",
  },
  ERANGE: {
    "name": "ERANGE",
    "number": 34,
    message: "Numerical result out of range",
  },
  EDEADLK: {
    "name": "EDEADLK",
    "number": 35,
    message: "Resource deadlock avoided",
  },
  ENAMETOOLONG: {
    "name": "ENAMETOOLONG",
    "number": 36,
    message: "File name too long",
  },
  ENOLCK: { "name": "ENOLCK", "number": 37, message: "No locks available" },
  ENOSYS: {
    "name": "ENOSYS",
    "number": 38,
    message: "Function not implemented",
  },
  ENOTEMPTY: {
    "name": "ENOTEMPTY",
    "number": 39,
    message: "Directory not empty",
  },
  ELOOP: {
    "name": "ELOOP",
    "number": 40,
    message: "Too many levels of symbolic links",
  },
  EWOULDBLOCK: {
    "name": "EWOULDBLOCK",
    "number": 11,
    message: "Resource temporarily unavailable",
  },
  ENOMSG: {
    "name": "ENOMSG",
    "number": 42,
    message: "No message of desired type",
  },
  EIDRM: { "name": "EIDRM", "number": 43, message: "Identifier removed" },
  ECHRNG: {
    "name": "ECHRNG",
    "number": 44,
    message: "Channel number out of range",
  },
  EL2NSYNC: {
    "name": "EL2NSYNC",
    "number": 45,
    message: "Level 2 not synchronized",
  },
  EL3HLT: { "name": "EL3HLT", "number": 46, message: "Level 3 halted" },
  EL3RST: { "name": "EL3RST", "number": 47, message: "Level 3 reset" },
  ELNRNG: {
    "name": "ELNRNG",
    "number": 48,
    message: "Link number out of range",
  },
  EUNATCH: {
    "name": "EUNATCH",
    "number": 49,
    message: "Protocol driver not attached",
  },
  ENOCSI: {
    "name": "ENOCSI",
    "number": 50,
    message: "No CSI structure available",
  },
  EL2HLT: { "name": "EL2HLT", "number": 51, message: "Level 2 halted" },
  EBADE: { "name": "EBADE", "number": 52, message: "Invalid exchange" },
  EBADR: {
    "name": "EBADR",
    "number": 53,
    message: "Invalid request descriptor",
  },
  EXFULL: { "name": "EXFULL", "number": 54, message: "Exchange full" },
  ENOANO: { "name": "ENOANO", "number": 55, message: "No anode" },
  EBADRQC: { "name": "EBADRQC", "number": 56, message: "Invalid request code" },
  EBADSLT: { "name": "EBADSLT", "number": 57, message: "Invalid slot" },
  EDEADLOCK: {
    "name": "EDEADLOCK",
    "number": 35,
    message: "Resource deadlock avoided",
  },
  EBFONT: { "name": "EBFONT", "number": 59, message: "Bad font file format" },
  ENOSTR: { "name": "ENOSTR", "number": 60, message: "Device not a stream" },
  ENODATA: { "name": "ENODATA", "number": 61, message: "No data available" },
  ETIME: { "name": "ETIME", "number": 62, message: "Timer expired" },
  ENOSR: { "name": "ENOSR", "number": 63, message: "Out of streams resources" },
  ENONET: {
    "name": "ENONET",
    "number": 64,
    message: "Machine is not on the network",
  },
  ENOPKG: { "name": "ENOPKG", "number": 65, message: "Package not installed" },
  EREMOTE: { "name": "EREMOTE", "number": 66, message: "Object is remote" },
  ENOLINK: {
    "name": "ENOLINK",
    "number": 67,
    message: "Link has been severed",
  },
  EADV: { "name": "EADV", "number": 68, message: "Advertise error" },
  ESRMNT: { "name": "ESRMNT", "number": 69, message: "Srmount error" },
  ECOMM: {
    "name": "ECOMM",
    "number": 70,
    message: "Communication error on send",
  },
  EPROTO: { "name": "EPROTO", "number": 71, message: "Protocol error" },
  EMULTIHOP: {
    "name": "EMULTIHOP",
    "number": 72,
    message: "Multihop attempted",
  },
  EDOTDOT: { "name": "EDOTDOT", "number": 73, message: "RFS specific error" },
  EBADMSG: { "name": "EBADMSG", "number": 74, message: "Bad message" },
  EOVERFLOW: {
    "name": "EOVERFLOW",
    "number": 75,
    message: "Value too large for defined data type",
  },
  ENOTUNIQ: {
    "name": "ENOTUNIQ",
    "number": 76,
    message: "Name not unique on network",
  },
  EBADFD: {
    "name": "EBADFD",
    "number": 77,
    message: "File descriptor in bad state",
  },
  EREMCHG: {
    "name": "EREMCHG",
    "number": 78,
    message: "Remote address changed",
  },
  ELIBACC: {
    "name": "ELIBACC",
    "number": 79,
    message: "Can not access a needed shared library",
  },
  ELIBBAD: {
    "name": "ELIBBAD",
    "number": 80,
    message: "Accessing a corrupted shared library",
  },
  ELIBSCN: {
    "name": "ELIBSCN",
    "number": 81,
    message: ".lib section in a.out corrupted",
  },
  ELIBMAX: {
    "name": "ELIBMAX",
    "number": 82,
    message: "Attempting to link in too many shared libraries",
  },
  ELIBEXEC: {
    "name": "ELIBEXEC",
    "number": 83,
    message: "Cannot exec a shared library directly",
  },
  EILSEQ: {
    "name": "EILSEQ",
    "number": 84,
    message: "Invalid or incomplete multibyte or wide character",
  },
  ERESTART: {
    "name": "ERESTART",
    "number": 85,
    message: "Interrupted system call should be restarted",
  },
  ESTRPIPE: { "name": "ESTRPIPE", "number": 86, message: "Streams pipe error" },
  EUSERS: { "name": "EUSERS", "number": 87, message: "Too many users" },
  ENOTSOCK: {
    "name": "ENOTSOCK",
    "number": 88,
    message: "Socket operation on non-socket",
  },
  EDESTADDRREQ: {
    "name": "EDESTADDRREQ",
    "number": 89,
    message: "Destination address required",
  },
  EMSGSIZE: { "name": "EMSGSIZE", "number": 90, message: "Message too long" },
  EPROTOTYPE: {
    "name": "EPROTOTYPE",
    "number": 91,
    message: "Protocol wrong type for socket",
  },
  ENOPROTOOPT: {
    "name": "ENOPROTOOPT",
    "number": 92,
    message: "Protocol not available",
  },
  EPROTONOSUPPORT: {
    "name": "EPROTONOSUPPORT",
    "number": 93,
    message: "Protocol not supported",
  },
  ESOCKTNOSUPPORT: {
    "name": "ESOCKTNOSUPPORT",
    "number": 94,
    message: "Socket type not supported",
  },
  EOPNOTSUPP: {
    "name": "EOPNOTSUPP",
    "number": 95,
    message: "Operation not supported",
  },
  EPFNOSUPPORT: {
    "name": "EPFNOSUPPORT",
    "number": 96,
    message: "Protocol family not supported",
  },
  EAFNOSUPPORT: {
    "name": "EAFNOSUPPORT",
    "number": 97,
    message: "Address family not supported by protocol",
  },
  EADDRINUSE: {
    "name": "EADDRINUSE",
    "number": 98,
    message: "Address already in use",
  },
  EADDRNOTAVAIL: {
    "name": "EADDRNOTAVAIL",
    "number": 99,
    message: "Cannot assign requested address",
  },
  ENETDOWN: { "name": "ENETDOWN", "number": 100, message: "Network is down" },
  ENETUNREACH: {
    "name": "ENETUNREACH",
    "number": 101,
    message: "Network is unreachable",
  },
  ENETRESET: {
    "name": "ENETRESET",
    "number": 102,
    message: "Network dropped connection on reset",
  },
  ECONNABORTED: {
    "name": "ECONNABORTED",
    "number": 103,
    message: "Software caused connection abort",
  },
  ECONNRESET: {
    "name": "ECONNRESET",
    "number": 104,
    message: "Connection reset by peer",
  },
  ENOBUFS: {
    "name": "ENOBUFS",
    "number": 105,
    message: "No buffer space available",
  },
  EISCONN: {
    "name": "EISCONN",
    "number": 106,
    message: "Transport endpoint is already connected",
  },
  ENOTCONN: {
    "name": "ENOTCONN",
    "number": 107,
    message: "Transport endpoint is not connected",
  },
  ESHUTDOWN: {
    "name": "ESHUTDOWN",
    "number": 108,
    message: "Cannot send after transport endpoint shutdown",
  },
  ETOOMANYREFS: {
    "name": "ETOOMANYREFS",
    "number": 109,
    message: "Too many references: cannot splice",
  },
  ETIMEDOUT: {
    "name": "ETIMEDOUT",
    "number": 110,
    message: "Connection timed out",
  },
  ECONNREFUSED: {
    "name": "ECONNREFUSED",
    "number": 111,
    message: "Connection refused",
  },
  EHOSTDOWN: { "name": "EHOSTDOWN", "number": 112, message: "Host is down" },
  EHOSTUNREACH: {
    "name": "EHOSTUNREACH",
    "number": 113,
    message: "No route to host",
  },
  EALREADY: {
    "name": "EALREADY",
    "number": 114,
    message: "Operation already in progress",
  },
  EINPROGRESS: {
    "name": "EINPROGRESS",
    "number": 115,
    message: "Operation now in progress",
  },
  ESTALE: { "name": "ESTALE", "number": 116, message: "Stale file handle" },
  EUCLEAN: {
    "name": "EUCLEAN",
    "number": 117,
    message: "Structure needs cleaning",
  },
  ENOTNAM: {
    "name": "ENOTNAM",
    "number": 118,
    message: "Not a XENIX named type file",
  },
  ENAVAIL: {
    "name": "ENAVAIL",
    "number": 119,
    message: "No XENIX semaphores available",
  },
  EISNAM: { "name": "EISNAM", "number": 120, message: "Is a named type file" },
  EREMOTEIO: {
    "name": "EREMOTEIO",
    "number": 121,
    message: "Remote I/O error",
  },
  EDQUOT: { "name": "EDQUOT", "number": 122, message: "Disk quota exceeded" },
  ENOMEDIUM: { "name": "ENOMEDIUM", "number": 123, message: "No medium found" },
  EMEDIUMTYPE: {
    "name": "EMEDIUMTYPE",
    "number": 124,
    message: "Wrong medium type",
  },
  ECANCELED: {
    "name": "ECANCELED",
    "number": 125,
    message: "Operation canceled",
  },
  ENOKEY: {
    "name": "ENOKEY",
    "number": 126,
    message: "Required key not available",
  },
  EKEYEXPIRED: {
    "name": "EKEYEXPIRED",
    "number": 127,
    message: "Key has expired",
  },
  EKEYREVOKED: {
    "name": "EKEYREVOKED",
    "number": 128,
    message: "Key has been revoked",
  },
  EKEYREJECTED: {
    "name": "EKEYREJECTED",
    "number": 129,
    message: "Key was rejected by service",
  },
  EOWNERDEAD: { "name": "EOWNERDEAD", "number": 130, message: "Owner died" },
  ENOTRECOVERABLE: {
    "name": "ENOTRECOVERABLE",
    "number": 131,
    message: "State not recoverable",
  },
  ERFKILL: {
    "name": "ERFKILL",
    "number": 132,
    message: "Operation not possible due to RF-kill",
  },
  EHWPOISON: {
    "name": "EHWPOISON",
    "number": 133,
    message: "Memory page has hardware error",
  },
  ENOTSUP: {
    "name": "ENOTSUP",
    "number": 95,
    message: "Operation not supported",
  },
};
