name: Deploy To Test Server

on:
  push:
    branches: [ testing ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
        emacs-version: [ 27.2 ]
    steps:
      - name: Checkout Repo + Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Emacs ${{ matrix.emacs-version }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Org-mode to Markdown
        run: |
          # emacs ./blog/content-org/all-posts.org --script scripts/build-blog.el --kill
          emacs ./blog/content-org/all-posts.org --batch -L ../../scripts -l build-blog.el --eval='(org-hugo-export-wim-to-md t)' --kill

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build blog
        run: |
          cd blog
          hugo --minify

      - name: Install NPM Dependencies and Build
        run: |
          cd client
          npm install
          npm run build --if-present

      - name: Run Jest Tests
        run: |
          cd client
          npm run test

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "client/dist/*"
          target: "${{ secrets.TEST_REMOTE_DIR }}"

      - name: Copy Share Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "share/*"
          target: "${{ secrets.TEST_PROJECT_ROOT }}/share"

      - name: Copy Blog Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "blog/public/*"
          target: "${{ secrets.TEST_PROJECT_ROOT }}"

      - name: Re-arrange File System
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd ${{ secrets.TEST_REMOTE_DIR }}/client/dist
            mv * ../..
            mv .well-known ../..
            cd ../..
            rm -rfv client/


            cd ${{ secrets.TEST_PROJECT_ROOT }}
            cd share
            mv share/* .
            rm -rfv share
            npm i
            
            cd ${{ secrets.TEST_PROJECT_ROOT }}
            cd blog
            mv public/* .
            rm -rfv public

            cd ..
            export HOME=${{ secrets.TEST_PROJECT_ROOT }}
            pm2 restart all --update-env ecosystem.config.js