name: Deploy To Server

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Emacs
        run: |
          sudo apt update -y
          sudo apt install emacs-nox -y

      - name: Setup ox-hugo
        run: git clone https://github.com/kaushalmodi/ox-hugo.git ox-hugo

      - name: Org-mode to markdown
        run: |
          emacs ./blog/content-org/all-posts.org --batch -L ../../ox-hugo -l ox-hugo.el --eval='(org-hugo-export-wim-to-md t)' --kill
#          rm -rf ox-hugo

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build blog
        run: |
          cd blog
          hugo --minify

      - name: Install NPM Dependencies and Build
        run: |
          cd client
          npm install
          npm run build --if-present

      - name: Run Jest Tests
        run: |
          cd client
          npm run test

      - name: Copy Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "client/dist/*"
          target: "${{ secrets.REMOTE_DIR }}"

      - name: Copy Share Files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "share/*"
          target: "${{ secrets.PROJECT_ROOT }}/share"

      - name: Re-arrange File System
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}/client/dist
            mv * ../..
            mv .well-known ../..
            cd ../..
            rm -rfv client/


            cd ${{ secrets.PROJECT_ROOT }}
            cd share
            mv share/* .
            rm -rfv share
            npm i

            cd ..
            export HOME=${{ secrets.PROJECT_ROOT }}
            pm2 restart all --update-env ecosystem.config.js