name: Frontend CI

on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    branches:
      - "*"
      - "!main"


jobs:
  run_tests_and_lint:
    name: Run Jest Tests & Lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install NPM Dependencies and Build
        run: |
          cd client
          npm install
          npm run build --if-present

      - name: Run ESLint
        run: |
          cd client
          npm run lint

      - name: Run Jest Tests
        run: |
          cd client
          npm run test
